package org.uminho.sgt.presentation;

import org.uminho.sgt.business.SGT;
import org.uminho.sgt.business.aulas.Turno;
import org.uminho.sgt.business.aulas.UnidadeCurricular;
import org.uminho.sgt.business.pessoal.Aluno;
import org.uminho.sgt.business.pessoal.Professor;
import org.uminho.sgt.business.pessoal.Utilizador;

import javax.swing.*;
import java.util.ArrayList;
import java.util.HashMap;

public class JProfessor extends javax.swing.JFrame {

  private SGT sgt;
  private Aluno aluno;
  private Professor professor;
  private HashMap<UnidadeCurricular, ArrayList<Turno>> cadeiras;
  private HashMap<String, UnidadeCurricular> listaUcs;
  // Variables declaration - do not modify
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton5;
  private javax.swing.JComboBox<Turno> jComboBox1;
  private javax.swing.JComboBox<UnidadeCurricular> jComboBox2;
  private javax.swing.JComboBox<Turno> jComboBox3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JList<Aluno> jList1;
  private javax.swing.JScrollPane jScrollPane1;

  public JProfessor(SGT sgt, Utilizador utilizador) {
    this.sgt = sgt;
    this.professor = (Professor) utilizador;
    this.cadeiras = this.professor.getCadeiras();
    this.listaUcs = this.sgt.getListaUCs();
    initComponents();

    jLabel3.setText(this.professor.getNome());
    jComboBox3.setEnabled(false);
    jComboBox1.setEnabled(false);
    jButton1.setEnabled(false);
    jButton5.setEnabled(false);
    jList1.setEnabled(false);
    if (this.professor.isIsDc()) {
      jButton2.setEnabled(true);
      jButton3.setEnabled(true);
      jComboBox2.addItem(null);
      for (String s : listaUcs.keySet()) {
        jComboBox2.addItem(listaUcs.get(s));
      }

    } else {
      jButton2.setVisible(false);
      jButton3.setVisible(false);
      jComboBox2.addItem(null);
      for (UnidadeCurricular u : cadeiras.keySet()) {
        jComboBox2.addItem(u);
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jButton1 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox<>();
    jComboBox3 = new javax.swing.JComboBox<>();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jLabel7 = new javax.swing.JLabel();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Menu Professor");

    jLabel2.setText("Bem vindo,");

    jLabel3.setText("professor");

    jList1.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            jList1MouseClicked(evt);
          }
        });
    jScrollPane1.setViewportView(jList1);

    jButton1.setText("Marcar Falta");
    jButton1.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
          }
        });

    jLabel4.setText("Mover aluno para:");

    jComboBox1.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
          }
        });

    jLabel5.setText("UC:");

    jLabel6.setText("Turno:");

    jComboBox2.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox2ActionPerformed(evt);
          }
        });

    jComboBox3.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox3ActionPerformed(evt);
          }
        });

    jButton2.setText("Gerar Turnos");
    jButton2.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
          }
        });

    jButton3.setText("Editar UC");
    jButton3.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
          }
        });

    jLabel7.setText("Turno:");

    jButton5.setText("Mover");
    jButton5.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(325, 325, 325)
                                    .addComponent(jLabel1))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(308, 308, 308)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jLabel5))
                                            .addComponent(jLabel6))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jComboBox3,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                85,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jComboBox2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                84,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(
                                jButton3,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jButton2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addGap(18, 23, Short.MAX_VALUE)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        341,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        jComboBox1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(
                                jButton5,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                100,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                    .addContainerGap(13, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(
                                                jComboBox1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton5))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(
                                                jComboBox2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(
                                                jComboBox3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton2)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                        jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        203,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(41, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    UnidadeCurricular u = (UnidadeCurricular) jComboBox2.getSelectedItem();
    Turno t = (Turno) jComboBox3.getSelectedItem();
    Aluno a = (Aluno) jList1.getSelectedValue();
    
    this.sgt.marcaFalta(u, t, a);
    updateList();
    jButton1.setEnabled(false);
  }

  private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
    UnidadeCurricular u = (UnidadeCurricular) jComboBox2.getSelectedItem();
    if (u == null) {
      jComboBox3.removeAllItems();
      jComboBox3.setEnabled(false);
      jComboBox1.removeAllItems();
      jComboBox1.setEnabled(false);
      jList1.setEnabled(false);
      jButton1.setEnabled(false);
      jButton5.setEnabled(false);
      clearList();
    } else {
      if (this.professor.isIsDc()) {
        jButton1.setEnabled(false);
        jButton5.setEnabled(false);
        jList1.setEnabled(false);
        jComboBox1.removeAllItems();
        jComboBox1.setEnabled(false);

        jComboBox3.removeAllItems();
        jComboBox3.addItem(null);
        for (Turno t : u.getTurnos()) {
          jComboBox3.addItem(t);
        }
      } else {
        jButton1.setEnabled(false);
        jButton5.setEnabled(false);
        jList1.setEnabled(false);
        jComboBox1.removeAllItems();
        jComboBox1.setEnabled(false);

        jComboBox3.removeAllItems();
        jComboBox3.addItem(null);
        for (UnidadeCurricular a : cadeiras.keySet()) {
          if (a.getNome().equals(u.getNome())) {
            for (Turno t : cadeiras.get(a)) {
              jComboBox3.addItem(t);
            }
          }
        }
      }
      jComboBox3.setEnabled(true);
    }
  }

  private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {
    Turno t = (Turno) jComboBox3.getSelectedItem();
    if (t == null) {
      jButton1.setEnabled(false);
      jButton5.setEnabled(false);
      jList1.setEnabled(false);
    } else {
      jButton1.setEnabled(false);
      jButton5.setEnabled(false);
      jList1.setEnabled(true);
      updateList();
    }
  }

  private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
    UnidadeCurricular u = (UnidadeCurricular) jComboBox2.getSelectedItem();
    Turno t = (Turno) jComboBox3.getSelectedItem();
    jButton1.setEnabled(false);

    if (t.getProfALecionar().getNumero() == this.professor.getNumero()) {
      this.aluno = jList1.getSelectedValue();
      if(this.aluno == null){
        jButton1.setEnabled(false);
      }else{
        jButton1.setEnabled(true);
      }
    }

    if (u.getRegente().getNumero() == this.professor.getNumero()) {
      jComboBox1.removeAllItems();
      jComboBox1.addItem(null);
      for (Turno a : u.getTurnos()) {
        if (a.getCapacidadeMaxima() != a.getFaltas().size()) {
          jComboBox1.addItem(a);
        }
      }
      jComboBox1.setEnabled(true);
    }
  }

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
    Turno t = (Turno) jComboBox1.getSelectedItem();
    if (t == null) {
      jButton5.setEnabled(false);
    } else {
      jButton5.setEnabled(true);
    }
  }

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
    UnidadeCurricular u = (UnidadeCurricular) jComboBox2.getSelectedItem();
    Turno origem = (Turno) jComboBox3.getSelectedItem();
    Aluno a = (Aluno) jList1.getSelectedValue();
    Turno destino = (Turno) jComboBox1.getSelectedItem();
    this.sgt.moveAluno(u, origem, destino, a);
    updateList();
  }

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {}

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    JEditarUC editar = new JEditarUC(this.sgt, this.listaUcs, this.sgt.getListaProfs());
    editar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    editar.setResizable(false);
    editar.setVisible(true);
  }
  // End of variables declaration

  private void updateList() {
    DefaultListModel<Aluno> lista = new DefaultListModel<Aluno>();
    Turno t = (Turno) jComboBox3.getSelectedItem();
    HashMap<Aluno, Integer> alunos = t.getFaltas();

    for (Aluno a : alunos.keySet()) {
      lista.addElement(a);
    }

    jList1.setModel(lista);
  }

  private void clearList() {
    DefaultListModel model = new DefaultListModel();
    model.clear();
    jList1.setModel(model);
  }
}
